# Generated by Django 3.1.1 on 2021-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='using',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('account', 'account')], max_length=100),
        ),
    ]
